### ISSUE TITLE
Client not authenticated!

### ISSUE THREAD

**Issue by Coime** [mircokroon/minecraft-world-downloader#109]
![em3D380Ce465fc8C0f](https://user-images.githubusercontent.com/42824671/107858196-fd150280-6e00-11eb-8c26-311c30327561.png)
Connecting to the proxy disconnects the client, and tells me that my client isn't authenticated.

```$ java -jar world-downloader.jar -s <ip> -r 16 --local-port 25566
Picked up _JAVA_OPTIONS: -Xmx5G
Starting proxy for <ip>. Make sure to connect to localhost:25566 instead of the regular server address.
java.lang.RuntimeException: Client not authenticated! {
  "error" : "ForbiddenOperationException",
  "path" : "/session/minecraft/join"
}
        at proxy.auth.ClientAuthenticator.makeRequest(ClientAuthenticator.java:206)
        at proxy.EncryptionManager.lambda$sendReplacementEncryptionConfirmation$6(EncryptionManager.java:225)
        at proxy.EncryptionManager.disconnectOnError(EncryptionManager.java:115)
        at proxy.EncryptionManager.sendReplacementEncryptionConfirmation(EncryptionManager.java:225)
        at proxy.EncryptionManager.lambda$setClientEncryptionConfirmation$5(EncryptionManager.java:213)
        at proxy.EncryptionManager.attempt(EncryptionManager.java:102)
        at proxy.EncryptionManager.setClientEncryptionConfirmation(EncryptionManager.java:202)
        at packets.handler.ServerBoundLoginPacketHandler.lambda$new$1(ServerBoundLoginPacketHandler.java:31)
        at packets.handler.PacketHandler.handle(PacketHandler.java:57)
        at packets.DataReader.readPackets(DataReader.java:163)
        at packets.DataReader.pushData(DataReader.java:118)
        at proxy.ProxyServer.lambda$run$4(ProxyServer.java:84)
        at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
        at proxy.ProxyServer.lambda$run$6(ProxyServer.java:81)
        at java.lang.Thread.run(Unknown Source)
Client probably disconnected. Waiting for new connection...
WARNING: packet parsing may have been incorrect! Expected length: 261. Used bytes: 0
Server probably disconnected. Waiting for new connection...
```

**Comment by mircokroon** [comment]
Did this happen just once or is it frequent?

**Comment by Coime** [comment]
> Did this happen just once or is it frequent?

Happens 100% of the time.

**Comment by mircokroon** [comment]
Are you using a custom launcher?

**Comment by Coime** [comment]
> Are you using a custom launcher?

Yes, but the problem still applies on vanilla.

**Comment by mircokroon** [comment]
These authentication issues are hard to debug, especially since there isn't really a useful error message when something goes wrong. I've changed around how the authentication works a little bit in [upcoming release 1.11](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.11). There may be some remaining issues.

Can you see if the issue is still present there? If automatic authentication doesn't work I suggest you try the manual method.

**Comment by mircokroon** [comment]
I'll assume this is fixed in the latest version

**Comment by Ari-RERA-43** [comment]
@mircokroon I'm still having this issue. Ive tried both copying the token out of MultiMC's accounts.json and using auto detect.

**Comment by mircokroon** [comment]
I'm intending to make some more changes to authentication in the future to fix this properly, for now I don't have a solution besides using the standard launcher unfortunately.

**Comment by Ari-RERA-43** [comment]
When I said I was using auto detect I was referring to using the vanilla launcher with auto detect.
